on:
  push:
    branches:
      - master
name: Test, Build and Release apk
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "microsoft"
          java-version: "11"
      - uses: subosito/flutter-action@v2
      - run: flutter pub get
      #- run: flutter test
      - run: flutter build apk
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: build/app/outputs/apk/release/app-release.apk
