name: Build and Release AAB

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "microsoft"
          java-version: "11"
      - uses: subosito/flutter-action@v2
      - run: flutter pub get
      - run: flutter test
      - run: flutter clean
      - run: flutter build appbundle --debug
      - uses: ncipollo/release-action@v1
        with:
          tag: 4.0.0
          artifacts: "build/app/outputs/bundle/debug/*.aab"
          token: ${{ secrets.TOKEN }}
