name: Build and Release APK

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "microsoft"
          java-version: "11"
      - uses: subosito/flutter-action@v2
      - run: flutter pub get
      #- run: flutter test
      - run: flutter build apk
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: build/app/outputs/apk/release/app-release.apk
